CREATE TABLE TB_CLIENTE (
	ID_CLIENTE SERIAL NOT NULL,
	NR_IDADE VARCHAR(2) NOT NULL,
	DT_ANIVERSARIO DATE,
	NM_GENERO VARCHAR(250) NOT NULL,
	NM_CLIENTE VARCHAR(250) NOT NULL,
    ID_CIDADE INTEGER NOT NULL,

    constraint fk_ID_CIDADE foreign key (ID_CIDADE) references TB_CIDADE(ID_CIDADE),
	constraint pk_ID_CLIENTE primary key (ID_CLIENTE)
);


INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "15", "2008-09-20", "M", "Thalys Welson", 6);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "18", "2005-07-28", "F", "Alice Terrara", 2);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "20", "2003-04-25", "F", "Analis Costa", 4);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "30", "1993-02-24", "M", "Severino dos Satos", 5);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "10", "2013-04-25", "F", "Erica da Silva", 4);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "35", "1988-01-01", "F", "Leila Maria", 3);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "40", "1983-02-20", "M", "Marconi Ferreia", 4);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "60", "1952-05-21", "M", "Pedro dos Santos", 1);
INSERT INTO TB_CLIENTE(ID_CLIENTE, NR_IDADE, DT_ANIVERSARIO, NM_GENERO, NM_CLIENTE, ID_CIDADE VALUES (nextval('seq_tb_cliente'), "25", "1997-04-28", "F", "Thalita Rodrigues", 2);